version: '3'
services:
  app-prod:
    image: pablooliva/ch.ckl.st-server:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    command: npm run rmt-dkr-prod
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"