version: '3.7'

networks:
  web:
    external: true

services:
  app-stage:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: chcklst-server-stage
    depends_on:
      - mongo-dev
    env_file: src/config/.env
    environment:
      - SERVER=local
    command: npm run prod
    ports:
      - '3000:3000'
    networks:
      - web
  mongo-stage:
    image: mongo:4.2.6
    container_name: chcklst-mongodb-stage
    ports:
      - '27017:27017'
    volumes:
    - './mongo/db/dev:/data/db'
    - './mongo/dump:/dump'
    - './src/config/secrets/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    env_file: src/config/.env
    networks:
      - web
