version: '3'
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "9229:9229"
  app-stage:
    image: pablooliva/ch.ckl.st-server:latest
    command: SERVER=local npm run prod
    ports:
      - "3000:3000"