version: '3.7'

networks:
  web:
    external: true

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: chcklst-server-dev
    depends_on:
      - mongo-dev
    command: npm run dev
    volumes:
      - '.:/app'
      - '/home/pablo/Documents/Apps/ch.ckl.st/user-images:/app/src/public/user-images'
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - web
  mongo-dev:
    image: mongo:4.2.6
    container_name: chcklst-mongodb-dev
    ports:
      - '27017:27017'
    volumes:
    - './mongo/db/dev:/data/db'
    - './mongo/dump:/dump'
    - './src/config/secrets/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    env_file: src/config/.env
    networks:
      - web
