version: '3.7'
services:
  app-dev:
    build:
      context: .
      dockerfile: docker/node/dev/Dockerfile
    container_name: nodejs
    command: npm run dev
    volumes:
      - '.:/app'
      - '/home/pablo/Documents/Apps/ch.ckl.st/user-images:/app/src/public/user-images'
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
      - mongo
    networks:
      - chcklst-internal
  app-stage:
    image: 'pablooliva/ch.ckl.st-server:latest'
    env_file: src/config/.env
    environment:
      - SERVER=local
    command: npm run prod
    ports:
      - '3000:3000'
  mongo:
    build: docker/mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
    - './mongo/db:/data/db'
    - './mongo/dump:/dump'
    env_file: src/config/.env
    networks:
      - chcklst-internal
networks:
  chcklst-internal:
    name: chcklst-net
