version: '3'
services:
  app-dev:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "9229:9229"
  app-stage:
    build: .
    command: npm run prod
    volumes:
      - .:/app
    ports:
      - "3000:3000"