version: '3'
services:
  app-prod:
    image: pablooliva/ch.ckl.st-server:latest
    container_name: chcklst-nodejs
    depends_on:
      - mongo-prod
    restart: always
    command: npm run prod
    expose:
      - 80
    volumes:
      - /home/chcklst/server/user-images:/app/dist/public/user-images
    env_file: ./.env
    environment:
      VIRTUAL_HOST: api.ch.ckl.st
      LETSENCRYPT_HOST: api.ch.ckl.st
      LETSENCRYPT_EMAIL: pablo@qecept.com
  mongo-prod:
    image: mongo:4.2.6
    container_name: chcklst-mongodb
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - './mongo/db/prod:/data/db'
      - './mongo/dump:/dump'
      - './src/config/secrets/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    env_file: ./.env
networks:
  default:
    external:
      name: nginx-proxy
