version: '3'
services:
  app-prod:
    image: pablooliva/ch.ckl.st-server:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    command: npm run prod
    env_file: ./.env
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/api.ch.ckl.st:/etc/letsencrypt/live/api.ch.ckl.st
      - /data/letsencrypt:/data/letsencrypt
      - /home/user-images:/dist/public/user-images