version: '3'

networks:
  web:
    external: true

services:
  app-prod:
    build:
      context: .
    container_name: chcklst-server-prod
    depends_on:
      - mongo-prod
    restart: always
    command: npm run prod
    expose:
      - 80
    volumes:
      - /home/chcklst/server/user-images:/app/dist/public/user-images
    env_file: ./.env
    networks:
      - web
  mongo-prod:
    image: mongo:4.2.6
    container_name: chcklst-mongodb-prod
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - './mongo/db/prod:/data/db'
      - './mongo/dump:/dump'
      - './src/config/secrets/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    env_file: ./.env
    networks:
      - web
